### ISSUE TITLE
Crash on v2023.1130.0

### ISSUE THREAD

**Issue by longnguyen2004** [goodtrailer/soyokaze#154]
<details>
<summary>Stack trace</summary>

```
2023-12-16 04:46:01 [error]: An unhandled error has occurred.
2023-12-16 04:46:01 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Rulesets.Scoring.HitEvent..ctor(Double, osu.Game.Rulesets.Scoring.HitResult, osu.Game.Rulesets.Objects.HitObject, osu.Game.Rulesets.Objects.HitObject, System.Nullable`1<osuTK.Vector2>)'.
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Soyokaze.Scoring.SoyokazeScoreProcessor.CreateHitEvent(JudgementResult result)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Scoring.ScoreProcessor.ApplyResultInternal(JudgementResult result)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Scoring.JudgementProcessor.ApplyResult(JudgementResult result)
2023-12-16 04:46:01 [error]: at osu.Game.Screens.Play.Player.<>c__DisplayClass93_0.<load>b__6(JudgementResult r)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.<.ctor>b__46_2(DrawableHitObject _, JudgementResult r)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.UI.Playfield.onNewResult(DrawableHitObject drawable, JudgementResult result)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.onNewResult(DrawableHitObject d, JudgementResult r)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.ApplyResult(Action`1 application)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Soyokaze.Objects.Drawables.DrawableHold.CheckForResult(Boolean userTriggered, Double timeOffset)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.UpdateResult(Boolean userTriggered)
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.UpdateAfterChildren()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Game.Rulesets.UI.FrameStabilityContainer.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-16 04:46:01 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2023-12-16 04:46:01 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

</details>

Should be fixed by recompiling I think

**Comment by goodtrailer** [comment]
Fixed with #162

Sorry for very late fix, I've been pretty busy haha.
