### ISSUE TITLE
`GameplaySkinComponentLookup` has been renamed to `SkinComponentLookup` on version 2024.906.2.0

### ISSUE THREAD

**Issue by LiarOnce** [goodtrailer/soyokaze#190]
Some logs:
```log
2024-09-26 08:45:32 [error]: Could not load ruleset "Soyokaze". Please check for an update from the developer.
2024-09-26 08:45:32 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2024-09-26 08:45:32 [verbose]: Could not load type 'osu.Game.Skinning.GameplaySkinComponentLookup`1' from assembly 'osu.Game, Version=2024.906.2.0, Culture=neutral, PublicKeyToken=null'.
2024-09-26 08:45:32 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2024-09-26 08:45:32 [verbose]: at System.Reflection.RuntimeModule.GetTypes()
2024-09-26 08:45:32 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2024-09-26 08:45:32 [verbose]: System.TypeLoadException: Could not load type 'osu.Game.Skinning.GameplaySkinComponentLookup`1' from assembly 'osu.Game, Version=2024.906.2.0, Culture=neutral, PublicKeyToken=null'.
2024-09-26 08:45:33 [verbose]: Opened realm "C:\Users\LiarOnce\AppData\Roaming\osu\client.realm" at version 42
```

On the latest bump PR, it looks have the same error:
```
/home/runner/work/soyokaze/soyokaze/osu.Game.Rulesets.Soyokaze/Skinning/SoyokazeSkinComponentLookup.cs(9,48): error CS0246: The type or namespace name 'GameplaySkinComponentLookup<>' could not be found (are you missing a using directive or an assembly reference?) 
```

commit: https://github.com/ppy/osu/commit/36b4013fa64857c23c70ab8f591bc2cc6b18c44f

**Comment by goodtrailer** [comment]
Thank you, fixed by #189 ([88885ee](https://github.com/goodtrailer/soyokaze/pull/189/commits/88885ee0f229baf28d07faab52c1fe2f11d886e6)) in newest release [2024.926.0](https://github.com/goodtrailer/soyokaze/releases/tag/2024.926.0).
